parameters:
#    hexmedia_knockout.example.class: Hexmedia\KnockoutBundle\Example

services:
#    hexmedia_knockout.example:
#        class: %hexmedia_knockout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
